language: node_js
node_js:
  - "11"

jobs:
  include:
    # - stage: Test
    #   install: yarn install --frozen-lockfile
    #   script: yarn test
    - stage: Lighthouse
      if: type = pull_request
      install: yarn install --frozen-lockfile
      script: yarn run lh --perf 90 --pwa 90 --a11y 90 --bp 90 --seo 90 "$(wait-for-netlify-preview)"